### ISSUE TITLE
Error on 1.0.5

### ISSUE THREAD

**Issue by bfjare** [kinoli/groupie#11] opened 2021-04-20 17:52 UTC
Running 
"craftcms/cms": "3.6.12",
"kinoli/groupie": "1.0.5",

I removed all other plugins to make sure that's not an issue.

<img width="1021" alt="Screen Shot 2021-04-20 at 11 51 25 AM" src="https://user-images.githubusercontent.com/11744681/115441992-c11a6700-a1ce-11eb-9004-6048328aa947.png">

When running 1.0.5 I get the following error.

<img width="928" alt="Screen Shot 2021-04-20 at 11 52 11 AM" src="https://user-images.githubusercontent.com/11744681/115442096-d98a8180-a1ce-11eb-81e2-b01d50dc2132.png">

If I revert the plugin back to 1.0.4, I can access settings again.

**Comment by kinoli** [comment] 2021-04-20 18:43
Verson 1.0.5 was a requested fix by the CraftCMS team to make Composer 2 work with the plugin. You will need to upgrade composer to v2.0+ or else just use 1.0.4. I suggest upgrading to the latest composer.

**Comment by bfjare** [comment] 2021-04-27 16:40
Issue still happens on server running Composer version 2.0.12

**Comment by kinoli** [comment] 2021-04-27 19:04
Is it working locally for you? What version of Composer do you have locally?

**Comment by kinoli** [comment] 2021-04-27 19:07
Can you try this. https://www.codegrepper.com/code-examples/shell/restart+composer

**Comment by bfjare** [comment] 2021-04-28 19:34
Local - works
![Screen Shot 2021-04-28 at 1 30 45 PM](https://user-images.githubusercontent.com/11744681/116461827-f6a1fe80-a825-11eb-9d9a-f21ff3016243.png)


Production - doesnt work
![Screen Shot 2021-04-28 at 1 29 53 PM](https://user-images.githubusercontent.com/11744681/116461734-d8d49980-a825-11eb-811d-faf11b545cb3.png)

**Comment by kinoli** [comment] 2021-06-22 04:51
This was caused by a namespacing issue that didn't appear on earlier composer versions and is fixed in the latest release. Upgrade the component to get the fix.

**Closed by kinoli** 2021-06-22 04:51 UTC

**Comment by bfjare** [comment] 2021-06-22 15:17
Thank you @kinoli !
